https://www.hackerrank.com/domains/python?badge_type=python&filters[subdomains][]=py-debugging&filters[subdomains][]=xml&filters[subdomains][]=numpy&filters[subdomains][]=closures-and-decorators

1-XML 1 - Find the Score

In [ ]:

import sys
import xml.etree.ElementTree as etree

def get_attr_number(node):
    count = 0
    for tag in node:
        count = count + get_attr_number(tag)
    return count + len(node.attrib)
if __name__ == '__main__':
    sys.stdin.readline()
    xml = sys.stdin.read()
    tree = etree.ElementTree(etree.fromstring(xml))
    root = tree.getroot()
    print(get_attr_number(root))

2-XML2 - Find the Maximum Depth

In [ ]:
import xml.etree.ElementTree as etree

maxdepth = 0
def depth(elem, level):
    global maxdepth
    if (level == maxdepth):
        maxdepth += 1
    for child in elem:
        depth(child, level + 1)
if __name__ == '__main__':
    n = int(input())
    xml = ""
    for i in range(n):
        xml =  xml + input() + "\n"
    tree = etree.ElementTree(etree.fromstring(xml))
    depth(tree.getroot(), -1)
    print(maxdepth)

3-Standardize Mobile Number Using Decorators

In [3]:
def wrapper(f):
    def fun(l):
        f(['+91 ' + c[-10:-5] + ' ' + c[-5:] for c in l])
    return fun

@wrapper
def sort_phone(l):
    print(*sorted(l), sep='\n')

if __name__ == '__main__':
    l = [input() for _ in range(int(input()))]
    sort_phone(l) 

1
919875641230
+91 98756 41230


4-Decorators 2 - Name Directory

In [4]:
import operator

def person_lister(f):
    def inner(people):

        return map(f, sorted(people, key=lambda x: int(x[2])))
    return inner

@person_lister
def name_format(person):
    return ("Mr. " if person[3] == "M" else "Ms. ") + person[0] + " " + person[1]

if __name__ == '__main__':
    people = [input().split() for i in range(int(input()))]
    print(*name_format(people), sep='\n')

1
Mike Thomson 20 M
Mr. Mike Thomson


5-Words Score

In [5]:
def is_vowel(letter):
    return letter in ['a', 'e', 'i', 'o', 'u', 'y']

def score_words(words):
    score = 0
    for word in words:
        num_vowels = 0
        for letter in word:
            if is_vowel(letter):
                num_vowels += 1
        if num_vowels % 2 == 0:
            score += 2
        else:
            score += 1
    return score

n = int(input())
words = input().split()
print(score_words(words))

2
hacker book
4


6-Arrays

In [7]:
import numpy

def arrays(arr):

    return(numpy.array(arr[::-1], float))
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


7-Shape and Reshape

In [6]:
import numpy
# Shape and Reshape in Python - Hacker Rank Solution START
print(numpy.array(input().split(), int).reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


9-Transpose and Flatten

In [9]:
import numpy
n, m = map(int, input().split())

storage = numpy.array([input().strip().split() for _ in range(n)], int)
print (storage.transpose())
print (storage.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


10-Concatenate

In [10]:
import numpy
P, N, M = map(int,input().split())
A = numpy.array([input().split() for _ in range(P)],int)
B = numpy.array([input().split() for _ in range(N)],int)
print(numpy.concatenate((A, B), axis = 0))

1 1 1
1 1 1
1 1 1
[[1 1 1]
 [1 1 1]]


11-Zeros and Ones

In [11]:
import numpy

N = tuple(map(int, input().split()))
print(numpy.zeros(N, int))
print(numpy.ones(N, int))

    3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


12-Eye and Identity

In [12]:
import numpy

numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))

    3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


13-Array Mathematics

In [13]:
import numpy

N, M = map(int, input().split())

A = numpy.array([list(map(int, input().split())) for n in range(N)])
B = numpy.array([list(map(int, input().split())) for n in range(N)])

print(A + B)
print(A - B)
print(A * B)
print(A // B)
print(A % B)
print(A ** B)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


14-Floor, Ceil and Rint

In [16]:
import numpy

numpy.set_printoptions(sign=' ')

array = numpy.array(input().split(),float)

print(numpy.floor(array))
print(numpy.ceil(array))
print(numpy.rint(array))

    1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


15-Sum and Prod

In [ ]:
import numpy

N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)], int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

16-Min and Max

In [15]:
import numpy

N, M = map(int, input().split())
storage = numpy.array([input().split() for _ in range(N)],int)
print(numpy.max(numpy.min(storage, axis=1), axis=0))

    4 2
      2 5      
3 7      
1 3      
4 0
3


17-Mean, Var, and Std

In [ ]:
import numpy

N,M = map(int, input().split())
l = []

for i in range(N):
    a = list(map(int, input().split()))
    l.append(a)

l = numpy.array(l)

numpy.set_printoptions(legacy='1.13')
print(numpy.mean(l, axis = 1))
print(numpy.var(l, axis = 0))
print(numpy.std(l))

18-Dot and Cross

In [17]:
import numpy

n = int(input())
a = numpy.array([input().split() for _ in range(n)], int)
b = numpy.array([input().split() for _ in range(n)], int)
print(numpy.dot(a, b))

2
1 2
1 2
3 4
3 4
[[ 9 12]
 [ 9 12]]


19-Inner and Outer

In [18]:
import numpy

A=list(map(int,input().split()))
B=list(map(int,input().split()))

print(numpy.inner(A,B))
print(numpy.outer(A,B))

    0 1      
2 3
3
[[0 0]
 [2 3]]


20-Polynomials

In [19]:
import numpy

poly = [float(x) for x in input().split()]
x = float(input())

print(numpy.polyval(poly, x))

1.1 2 3
0
3.0


21-Linear Algebra

In [21]:
import numpy
N = int(input())
A = numpy.array([input().split() for _ in range(N)], float)
print(round(numpy.linalg.det(A),2))

2
1.1 1.1
1.1 1.1
0.0
